### ISSUE TITLE
Testing app

### ISSUE THREAD

**Issue by Paarth002** [TheInsightDevelopers/InsightAndroid#14]
Feedback:
1) Registration failed for 4-character password (There should be a comment/indication why registration failed)
2) Confirm password didn't match but successfully registered
3) I forgot password and can't login again :'( . (Yes it was my mistake, but can't login since I forgot mail also)

**Comment by Amar-2003** [comment]
@Paarth002 if you look carefully in login screen there is forgot password option, so the third one is irrelevant. Rest two are noted.;)

**Comment by Amar-2003** [comment]
Also the authentication requires a four character password

**Comment by Amar-2003** [comment]
Thanks @Paarth002 for your review
