### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by anir-ab** [TheInsightDevelopers/InsightAndroid#15]
1) Reply to person (by @) is not working
2) After deleting the instructor account I can still send messages and access the files
3) In the edit profile page for the student background/text-color should be changed (I can't see any text)

**Comment by Amar-2003** [comment]
Thanks @anir-ab , actually we haven't thought of making a feature of "@" calling. Rest bugs are noted :)

**Comment by Amar-2003** [comment]
> 1. Reply to person (by @) is not working
> 2. After deleting the instructor account I can still send messages and access the files
> 3. In the edit profile page for the student background/text-color should be changed (I can't see any text)

After deleting the account are you redirected to the the login screen ??

**Comment by Amar-2003** [comment]
the 3 rd one mentioned has been done, and 1st one wouldn't be possible for the next update, But would surely do later

**Comment by Amar-2003** [comment]
@anir-ab Please update the 2nd one

**Comment by anir-ab** [comment]
2nd issue update 
After signing out( for both instructor and student) account and pressing back,  one can still access the files and chats
