### ISSUE TITLE
Making soft input in all screens

### ISSUE THREAD

**Issue by Amar-2003** [TheInsightDevelopers/InsightAndroid#16]
In android Manifest file, add "android:windowSoftInputMode="adjustResize"" in every activity tag without quotes, pls do it @sksusha8853

**Comment by Amar-2003** [comment]
An example in case of login screen is <activity android:name=".LoginPage" android:windowSoftInputMode="adjustResize"/>, pls follow this @sksusha8853

**Comment by Amar-2003** [comment]
<activity android:name=".LoginPage" android:windowSoftInputMode="adjustResize"/> - Example

**Comment by Amar-2003** [comment]
"<activity android:name=".LoginPage" android:windowSoftInputMode="adjustResize"/>"

**Comment by Amar-2003** [comment]
{{{{<activity android:name=".LoginPage" android:windowSoftInputMode="adjustResize"/>}}}

**Comment by sksusha8853** [comment]
It is already there

**Comment by Amar-2003** [comment]
> It is already there

Not for every activity tag

**Comment by Amar-2003** [comment]
Make it for all activity tags

**Comment by Amar-2003** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.insights">
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-feature android:name="android.hardware.touchscreen" android:required="false"/>
<uses-feature android:name="android.software.leanback" android:required="true"/>
<application android:allowBackup="true" android:banner="@color/black" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/NoActionBarTheme">
<activity android:name=".pdfViewActivity"/>
<activity android:name=".InstructorEditProfileActivity"/>
<activity android:name=".InstructorProfileActivity"/>
<activity android:name=".UploadVideoActivity"/>
<activity android:name=".BookUploadActivity"/>
<activity android:name=".ForumnActivity"/>
<activity android:name=".student_profile"/>
<activity android:name=".mainPageNew"/>
<activity android:name=".studentEditProfile"/>
<activity android:name=".Junction"/>
<activity android:name=".ForgotPasswordActivity"/>
<activity android:name=".MainActivity">
<intent-filter>
<action android:name="android.intent.action.MAIN"/>
<category android:name="android.intent.category.LAUNCHER"/>
</intent-filter>
</activity>
<activity android:name=".LoginPage" android:windowSoftInputMode="adjustResize"/>
<activity android:name=".Student" android:windowSoftInputMode="adjustResize"/>
<activity android:name=".Instructor" android:windowSoftInputMode="adjustResize"/>
</application>
</manifest>

**Comment by sksusha8853** [comment]
![is this](https://user-images.githubusercontent.com/77530794/113087485-52667100-9201-11eb-8041-e589a9de0a8c.png)

**Comment by sksusha8853** [comment]
Is this fine

**Comment by Amar-2003** [comment]
All Cool :)

**Comment by Amar-2003** [comment]
In PR add the line FIx #16

**Comment by sksusha8853** [comment]
Do I need to create new PR

**Comment by Amar-2003** [comment]
Yes to beta 1.0 with Fix #16 in the description
