### ISSUE TITLE
Change Icon name and Icon

### ISSUE THREAD

**Issue by Amar-2003** [TheInsightDevelopers/InsightAndroid#32]
**Describe the bug**
In the MainPageNew activity, the Home icon should be replace with Video Icon and name Video
**To Reproduce**
1. Open the App
2. See the error

**Expected behavior**
It should be Video and Video Icon

**Screenshots**

![20210402_075739](https://user-images.githubusercontent.com/73783193/113373783-3c83b800-9389-11eb-9601-99b9b3cde958.jpg)

**Comment by Pranav915** [comment]
Hey,
I am solving this Issue
