### ISSUE TITLE
change ItemAdapter2 class name

### ISSUE THREAD

**Issue by Amar-2003** [TheInsightDevelopers/InsightAndroid#53]
The ItemAdapter2 is used for Displaying Video recylerlist, but it isn't named properly.It should be renamed to VideoRecyclerViewAdapter in the files ItemAdapter2.kt and HomeFragment.kt.
Reference PR #49.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue.

**Comment by Amar-2003** [comment]
Yeah go On
