### ISSUE TITLE
Cannot Install New Version

### ISSUE THREAD

**Issue by Sutanup** [TheInsightDevelopers/InsightAndroid#67]
Yup, I can't install it. 

https://user-images.githubusercontent.com/81879137/115473560-90334400-a259-11eb-8bff-66b885da1676.mp4

Try it yourself. @Gkm4430  can't as well.

**Comment by Amar-2003** [comment]
Its working fine in ,my device @Sutanup , let me see

**Comment by Amar-2003** [comment]
@Sutanup , fixed checkout the new apk, the previous one was broken
