### ISSUE TITLE
Text alignment in Forum Edit text

### ISSUE THREAD

**Issue by Amar-2003** [TheInsightDevelopers/InsightAndroid#69]
Currently the edit text in forumn aligns text centrally, but it doesn't look, so the text inside the edit text should start from left.
The file to be changed is activity_forum.xml.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please assign me this issue

**Comment by Amar-2003** [comment]
Hello @himanshu007-creator , sorry to say this issue was already claimed, wasn't marked assigned.Try finding someother ones in the repository
