### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by Amar-2003** [TheInsightDevelopers/InsightAndroid#7]
Any suggestions to this page
@sksusha8853 @ash-100 @Gkm4430

**Comment by Amar-2003** [comment]
![Screenshot_20210330-160538_Insight.jpg](https://user-images.githubusercontent.com/73783193/112975883-d07b3700-9171-11eb-8620-64a89339e39f.jpg)

**Comment by Gkm4430** [comment]
Looks good

**Comment by Amar-2003** [comment]
Thanks @Gkm4430
