### ISSUE TITLE
Checks for null entry

### ISSUE THREAD

**Issue by Amar-2003** [TheInsightDevelopers/InsightAndroid#72]
Users don't enter there name and datas while registering, to make sure user has entered, checks should be made so that it returns a toast if left blank.File to be modified Student.kt and Instructor.kt

**Comment by PorkStew** [comment]
I would like to contribute to this issue. What did you mean by “datas”? Would you like all EditText fields to be checked for null values or do you have specific ones like name?

**Comment by Amar-2003** [comment]
> I would like to contribute to this issue. What did you mean by “datas”? Would you like all EditText fields to be checked for null values or do you have specific ones like name?

Hi, thanks for showing interest, Yes all edit texts should be checked for null values, By data I meant the input from the user
